### ISSUE TITLE
Click on Select Bank randomly get blocked

### ISSUE THREAD

**Issue by Diego-Franco** [plaid/react-native-plaid-link-sdk#102]
Using this new sdk I was checking on the iOS simulator and some times some tiles (banks) are not tappable, this happens randomly:

**rn-plaid-link-sdk version:** `3.1.2`
**react-native version:** `0.61.5`

Clicks with errors
<img src="https://user-images.githubusercontent.com/5623933/77970568-60f21380-72a1-11ea-9eed-da72d1dc1f5f.gif" width=200 height=400/>

Clicks without errors
<img src="https://user-images.githubusercontent.com/5623933/77971077-ac58f180-72a2-11ea-93e6-b4ba242bcf75.gif" width=200 height=400/>

**Comment by JeroenMols** [comment]
This is a great find! Sorry for not following up on this before.

Since filing this issue we've made many changes under the hood:

1. v2 LinkKit (iOS SDK)
1. redesigned all Link screens
1. update react native SDK to support typescript 

Especially the first change makes the issue you reported obsolete as the search & select screen has been re-implemented. Please don't hesitate to report a new issue should you still see this.
