### ISSUE TITLE
Account ids are missing on the account objects after successfully linking on IOS

### ISSUE THREAD

**Issue by MariaTolstov** [plaid/react-native-plaid-link-sdk#254]
# The problem

After successfully linking a card, the data from onSuccess callback is missing the account ids. When getting the same accounts using the api, the ids are there.
<img width="799" alt="Screen Shot 2020-11-11 at 18 01 28" src="https://user-images.githubusercontent.com/2087786/98840932-1a2be500-2450-11eb-979d-c8a07beafe3e.png">

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | e.g. 6.0.0                |
| ReactNative Version     | e.g. 0.60.5                |
| Occurs on Android             | e.g. no                |
| Occurs on iOS     | yes |
| iOS Version           | e.g. 12                |
| iOS Devices/Emulators               | e.g. iPhone 8  |

**Comment by cloudmanic** [comment]
Totally having this issue too. Any help would be amazing!

**Comment by amytang0** [comment]
Hi, can you update to 6.0.3 and see if this repros still? Thanks!

**Comment by caiokf** [comment]
We are having the same issue:

Using 

```
"react-native": "0.62.2",
"react-native-plaid-link-sdk": "^5.0.0",
```

We had our plaid integration working until a few days ago. Without any changes to our codebase or installed modules, Plaid integration stopped working. We traced the issue to the data from a `onSuccess` callback no longer returning account ids and other account metadata once an account has successfully being linked. This problem was happening on android and ios.

Example response:
```
{"account": {"id": null, "mask": null, "name": null, "subtype": null, "type": null}, "account_id": null, "accounts": [{"id": null, "mask": "0000", "name": "Plaid Checking", "subtype": "checking", "type": "depository"}], "institution": {"institution_id": "ins_3", "name": "Chase"}, "link_session_id": "XXXX", "public_token": "public-sandbox-XXXX", "request_id": null}
```

Attempting to update plaid and ios Pod to versions:

```
"react-native-plaid-link-sdk": "^6.0.3",
pod 'Plaid', '~>2.0.6' 
```

This fixes android, but does not build the ios app because:
```
cp: /Users/<PROJECT>/ios/Pods/Plaid/ios/LinkKit.framework/prepare_for_distribution.sh: No such file or directory
/Users/caiokf/Library/Developer/Xcode/DerivedData/<APP>-axxlilyvzisqirbxxsejdqduosmv/Build/Intermediates.noindex/<APP>.build/Debug-iphonesimulator/QA.build/Script-E6061D2D24ECBF7F001DB1CD.sh: line 6: /Users/user/Library/Developer/Xcode/DerivedData/genoa-axxlilyvzisqirbxxsejdqduosmv/Build/Products/Debug-iphonesimulator/Flex - QA.app/Frameworks/LinkKit.framework/prepare_for_distribution.sh: No such file or directory
```

**Comment by petecroaker** [comment]
We've got the same issue, but it has been fine up until recently. Android still works fine, but with iOS, the account objects are missing ids.

We're using v4.01 with Plaid pod v1.1.35

We're not keen to update to v6 as it seems that this requires updating the minimum iOS version from 10 to 11.

**Comment by AnkurGahtori2012** [comment]
![Screenshot 2020-11-16 at 12 36 09 PM](https://user-images.githubusercontent.com/60691396/99222428-90419a80-2808-11eb-8c26-093a8ea9e42b.png)
we are using react-native-plaid-link-sdk version 3.2.0 facing same issue with ios

**Comment by dwh2427** [comment]
I have informed Plaid. I believe it was their oversight that they fixed this in iOS link and updated status.plaid.com without fixing the same for react native. Suggest you contact your account manager if you are having this issue as they can push an immediate fix for your account

**Comment by MariaTolstov** [comment]
Updating to react-native-plaid-link-sdk 6.0.3 fixed the issue for us.

**Comment by AnkurGahtori2012** [comment]
> Updating to react-native-plaid-link-sdk 6.0.3 fixed the issue for us.

@MariaTolstov Thanks for the update, but I am using react-native 0.60, react-native-plaid-link-sdk 6.0.3 is compatible with react-native ^0.61.3 at this moment I can't update the react-native version.

**Comment by jeremyricketts** [comment]
We consider this an urgently needed fix as we have an iOS app with wide distribution that is currently broken because of this bug.

**Comment by juddblair** [comment]
Hi y'all, super sorry for the problems you're having here - the root cause here is related to a bug in the < 1.3.38 iOS SDK that surfaced when we rolled out our redesign of Link late last week. A couple things:

1. Please shoot me an email at jblair@plaid.com and we can put you back on our old designs and mitigate the issue.
2. Upgrading to 1.3.38 on the iOS side will fix the issue, at which point you can let us know and we can move you back to new Link. You shouldn't have to upgrade the RN SDK if you're on 5.x.x or above, although we do have a major RN version coming out soon if you're looking to upgrade both.

Again, super sorry y'all.

**Comment by petecroaker** [comment]
Thanks @juddblair...updating to v4.01 with Plaid pod v1.1.38 fixed the issue!

**Comment by AnkurGahtori2012** [comment]
Thanks @juddblair it worked for me.
IOS 1.1.38
RN SDK 5.0.1
But now in case of registering an account using microDeposit method, I am not getting field verification_status for the registered bank. 
With old environment I was getting "verification_status" with account data on onSuccess callback.

**Comment by cloudmanic** [comment]
So how do you upgrade to Plaid pod v1.1.38 ?
