### ISSUE TITLE
LinkEventName is missing "acknowledged"

### ISSUE THREAD

**Issue by a613** [plaid/react-native-plaid-link-sdk#357]
# The problem

The `LinkEventName` enum is missing the `acknowledged` event.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.0.2      |
| ReactNative Version     | 0.63.3              |
| Occurs on Android             | yes           |
| Android OS Version                    | 11           |
| Android Devices/Emulators    | sim         |
| Occurs on iOS     | unknown              |

# Steps to Reproduce

1. get link token using `android_package_name`
2. initiate Link using the token
3. choose the oauth test bank
4. select successful consent
5. click continue
6. notice event that comes in is `acknowledged` which is missing from `LinkEventName`

# Expected Result

`LinkEventName` should have all event names

# Screenshots

N/A

# Logs

N/A

# Code To Reproduce Issue 

N/A

**Comment by zsweigart** [comment]
Hi @a613 Thanks for the feedback. Event names are subject to addition and removal at any time with the exception of `OPEN`, `EXIT`, `HANDOFF`, `SELECT_INSTITUTION`, and `ERROR`

Because of this, some events may not be present in certain versions of the SDK. We do not plan to add the `acknowledged` event at this time.

Please see our docs to learn more. https://plaid.com/docs/link/react-native/#onevent
