### ISSUE TITLE
you may need to update your app in order to connect to Wells Fargo

### ISSUE THREAD

**Issue by zhuxiaozhuworking** [plaid/react-native-plaid-link-sdk#428]
# The problem
when connnect to Wells Fargo , notice me to update 

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | e.g. 7.1.1                |
| ReactNative Version     | e.g. 0.61.1                |
![Uploading WechatIMG373.jpeg…]()

**Comment by afh** [comment]
@zhuxiaozhuworking it seems the screenshot was not properly uploaded. Can you share it again please?

**Comment by jordanhbuiltbyhq** [comment]
We are encountering this same issue with a web view in Android and the iOS SDK
![Screenshot_20211130-103135_Lively](https://user-images.githubusercontent.com/15804476/144100534-2f174dbb-be67-499c-a80d-8adc8afb3611.jpg)

**Comment by jordanhbuiltbyhq** [comment]
Reached out to support and received this very helpful reply for anyone else who encounters this!

Plaid recently deprecated the old institution integrations for both Wells Fargo and Chase. As of September 30, 2021, the legacy non-OAuth Chase flow (ins_3) and Wells Fargo flow (ins_4) are no longer available in Plaid Link. You should already be enabled for Chase OAuth (ins_56) and Wells Fargo Oauth (ins_127991), so if your Link integration is set up to support OAuth for your entire user base, you will not experience any disruption to your Chase access.

However if your Link integration is not fully set up to correctly handle OAuth, a portion of your Chase and Wells Fargo users may still be getting routed to the legacy non-OAuth flow (ins_3 and ins_4 respectively). After Sep 30, these users will no longer be routed to the non-OAuth flow and will instead encounter an error in Link.

To avoid disruption and ensure 100% of your Chase users are able to continue linking, please take a moment to review the checklist below to ensure your Plaid Link integration is fully compatible with OAuth for all your users.

OAuth checklist:

Migrate to Link tokens. If you are still using the legacy public key-based Link integration, be sure to migrate to Link tokens.

Pass in your OAuth redirect URI. Ensure you have configured at least one OAuth redirect URI in your Dashboard and that 100% of your /link/token/create calls include the redirectUri parameter. (Note this is not necessary for desktop web Link integrations)

Implement OAuth in Link Update Mode. If you use Link Update Mode, ensure that the OAuth updates you've implemented for your main Plaid Link flow are similarly applied to Update Mode.

Upgrade Link SDKs. If you use one of our Link SDKs, be sure your users are using versions no earlier than LinkKit 1.1.24 (iOS) and 1.4.0 (Android). In any case, we strongly recommend adopting the latest releases if possible (LinkKit 2.1.3 for iOS and 3.4.1 for Android), especially since Android v3.2.3+ is required to support Wells Fargo OAuth.

Update institution IDs. If you are passing an institution ID into your Link initializations, be sure to replace the legacy non-OAuth Chase institution ID (ins_3) with the Chase OAuth institution ID (ins_56) and legacy non-OAuth Wells institution ID (ins_4) with the Wells OAuth institution ID (ins_127991).

Additionally, please ensure that these updates are pushed out to your full customer base (we'd suggest forcing app upgrades as needed).

**Comment by amytang0** [comment]
Thank you Jordan, this is the correct answer!
Certain institutions are requiring access to their data via OAuth, which is only supported with a Link token integration.
