### ISSUE TITLE
Link closes automatically

### ISSUE THREAD

**Issue by 7patricia** [plaid/react-native-plaid-link-sdk#48]
Hi! 

I'm using `openLink` alone to open the link without showing any UI element before, but a strange behaviour is happening: if I don't wrap it in a `setTimout` it opens and it automatically closes right after. If I wrap it in a `setTimout` it works perfectly.

Here's how I'm doing it: 

```
import { openLink } from 'react-native-plaid-link-sdk';
...
render () {
  return (
    <Component onPress={this.openPlaidLink}>
    ...
    </Component>
  );
}
...
openPlaidLink() {
    setTimeout(
      () =>
        openLink({
          clientName: 'foobar',
          env: get(plaid, 'environment'),
          onSuccess: response =>
            BankAccountUtils.onPlaidLinkSuccess(response, onFailed, onPending, onSuccess, navigation),
          product: ['auth', 'identity'],
          publicKey: get(plaid, 'publicKey')
        }),
      100
    );
}
```
Does somebody have any idea on why this might be happening?

Obs: I'm using `v2.0.4`

Thank you!

**Comment by 7patricia** [comment]
Hi! This is still happening to me on v3.0.1.

**Comment by zsweigart** [comment]
Hi @7patricia Thanks for the report, we had not designed the SDK to open link without using the component.  We'll look into how to make this possible

**Comment by maitham** [comment]
Yea this is super annoying do we have timeline for this? Seems to only happen in production mode.

**Comment by SandroMachado** [comment]
@zsweigart any updates?

**Comment by amytang0** [comment]
Hi Sandro,
We currently don't have the ability to open Plaid Link without the component on our roadmap.
Can I ask why you all would want to? It would help us determine whether to add to our timelines.

Thanks!
Amy

**Comment by SandroMachado** [comment]
Hi @amytang0,

IMO opening without a component (using an imperative API) should be the default behaviour on React Native. On mobile devices the screens are small, what most of the developers that integrate plaid should do is open the plaid component in a new screen when the user presses a button. At least we are doing that. To do that we need a imperative API otherwise the users will se a rendering and a strange effect.

If you have any doubts please let me know. 

Thanks for the reply.

**Comment by zsweigart** [comment]
Hi @SandroMachado  and @7patricia can you try with version 6.0.3?

**Comment by SandroMachado** [comment]
Tried with the latest version and the issue persists.

**Comment by robertocropper** [comment]
My Link was working last week, come back to this project and suddenly started closing automatically when spinner shows, happening on iOS.

**Comment by pladaub** [comment]
@robertocropper that is likely a different issue. Could you file a new issue with steps to reproduce and info about your SDK version?

**Comment by marcaaron** [comment]
>we had not designed the SDK to open link without using the component. We'll look into how to make this possible

Just curious, is this still not possible?  It does seem like the expected behavior of `openLink()` (although looking again it does not seem to be well documented).

>IMO opening without a component (using an imperative API) should be the default behaviour on React Native

I agree with this e.g. in our app we are using an imperative style, but now I'm wondering if that approach is causing issues for us as it's not actually supported.

>Can I ask why you all would want to?

The `react-plaid-link` package mentions this is the "the preferred approach for integrating with Plaid Link in React"

https://github.com/plaid/react-plaid-link#using-react-hooks

I naturally assumed the same would be true for this package 😄  

I think really one problem with not having the imperative option (besides causing confusion) is that it forces the Plaid Link flow to be triggered by a `Pressable` `onPress` event which is just less flexible than allowing it to open based on whatever style of interaction a developer chooses (or to execute in series with other actions on press).
